#! /usr/bin/python3

import argparse as ap
import urllib.request
import urllib.parse
import subprocess
import json
import re

parser = ap.ArgumentParser(description='a simple tool that lets you play songs using YouTube from the cli')
parser.add_argument('--query', type=str, help='search YouTube for given search query')
parser.add_argument('--info', type=str, help='retrieve video info for given video id')
args = parser.parse_args()

if args.query != None:
    query_string = urllib.parse.urlencode({"search_query" : args.query})
    html = urllib.request.urlopen("https://www.youtube.com/results?search_query=" + query_string)
    search_results = re.findall(r"watch\?v=(\S{11})", html.read().decode())
    print("http://www.youtube.com/watch?v=" + search_results[0])

if args.info != None:
    jsonstr = urllib.request.urlopen("https://noembed.com/embed?url=" + args.info).read().decode('utf-8')
    video_info = json.loads(jsonstr)
    YELLOW='\033[0;33m'
    RESET_ALL='\033[0m'
    print(YELLOW + 'Title: ' + RESET_ALL + video_info['title'])
    print(YELLOW + 'Uploader: ' + RESET_ALL + video_info['author_name'])
