#! /bin/bash

WORKING_DIR="/home/$USER/.songs"
TARGET_PLAYER='mpv'

show_help(){
	echo help
}

inv_par(){
	echo inv
}

play_song(){
	link="$(ytcli --query "$1")"
        file=$(echo "$link" | sed 's/.*=//')
        info="$(ytcli --info "$link")"
        echo -e $info && echo
        info="`echo $info | head -1`"
        if [ -f "$WORKING_DIR/$file" ]; then
                mpv $WORKING_DIR/$file
        else
                echo -e "${info%%Uploader: *}\t|\t\033[0;32m$file" >> $HOME/.songs/saved
                youtube-dl -f 251 --audio-format "aac" -o - "$link" | tee "$file" | mpv -
        fi
}

cd $WORKING_DIR

case "$#" in
	"0")
		show_help
		;;

	"1")
		case "$1" in
			'-h'|'--help')
				show_help
			;;

			'-i'|'--info')
				cat $HOME/.songs/saved
				du -hs $WORKING_DIR
			;;
		esac
		;;

	"2")
		case "$1" in
			'-p'|'--play')
				play_song "$2"
			;;
		esac
		;;
	
	*)
		if [ "$1" = "-p" ] || [ "$1" = "--play" ]; then
			play_song "${@:2}"
		else
			inv_par
		fi
		;;
esac
